name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Docker build && push
      run: |
#        docker login docker.pkg.github.com --username icqparty
        docker tag app docker.pkg.github.com/icqparty/repo/docker-github-actions-runner:1.0
        docker push docker.pkg.github.com/icqparty/repo/docker-github-actions-runner:1.0