name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: self-hosted

    steps:
#    - name: Docker login
#      run: docker login docker.pkg.github.com --username icqparty
    - name: Dcoker push
      run: |
        docker tag app docker.pkg.github.com/icqparty/repo/docker-github-actions-runner:1.0
        docker push docker.pkg.github.com/icqparty/repo/docker-github-actions-runner:1.0