name: Publish Docker
on:
  push:
    tags:
      - '*'

jobs:
  ubuntu_tag_deploy:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      run: |
        docker login docker.pkg.github.com --username phanatic