name: Publish Docker
on:
  push:
    tags:
      - '*'

jobs:
  ubuntu_tag_deploy:
    runs-on: self-hosted
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master
    - name: get version
      run: echo "::set-env name=TAG::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")"
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build
      run: docker buildx build -f Dockerfile.ubuntu -t icqparty/github-runner:${TAG} --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
